#spring.application.name=GateWay
server:
  port: 3000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalCors:
        cors-configurations:
          '[/**]': # 匹配所有路径
            allowedOrigins: 
              - "http://localhost:8079"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*" # 允许所有请求头
            allowCredentials: true
      routes:
#        go
        - id: appeal-service
          uri: http://localhost:8093
          predicates:
            - Path=/api-8093/**
        - id: chat-service
          uri: http://localhost:8088
          predicates:
            - Path=/api-8088/**
        - id: comment-service
          uri: http://localhost:8091
          predicates:
            - Path=/api-8091/**
#      java
        - id: admin-login-service
          uri: http://localhost:8094
          predicates:
            - Path=/api-8094/**
        - id: wallet-service
          uri: http://localhost:8081
          predicates:
            - Path=/api-8081/**
        - id: profile-service
          uri: http://localhost:8089
          predicates:
            - Path=/api-8089/**
        - id: product-query-service
          uri: http://localhost:8096
          predicates:
            - Path=/product-query/api-8096/**
        - id: order-management-service
          uri: http://localhost:8095
          predicates:
            - Path=/api-8095/**
        - id: ban-service
          uri: http://localhost:8082
          predicates:
            - Path=/api-8082/**
        - id: login-service
          uri: http://localhost:8080
          predicates:
            - Path=/api-8080/**
        - id: product-management-seller-service
          uri: http://localhost:8084
          predicates:
            - Path=/api-8084/**
        - id: view-latest-service
          uri: http://localhost:8087
          predicates:
            - Path=/api-8087/**
        - id: view-product-info-service
          uri: http://localhost:8083
          predicates:
            - Path=/api-8083/**
        - id: nearby-service
          uri: http://localhost:8086
          predicates:
            - Path=/api-8086/**
        - id: cart-service
          uri: http://localhost:8085
          predicates:
            - Path=/api-8085/**
        - id: announcement-service
          uri: http://localhost:8092
          predicates:
            - Path=/api-8092/**
#        python
        - id: python-service
          uri: http://localhost:8000
          predicates:
            - Path=/api/v1/commodities/**

  main:
    web-application-type: reactive

#  ?????????
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: "*" # ???? Actuator ??
  endpoint:
    gateway:
      enabled: true # ?? Spring Cloud Gateway ? Actuator ??
#  main:
#    web-application-type: reactive
