server:
  port: 8084

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://rm-cn-smw4b7vtl0001ho.rwlb.rds.aliyuncs.com/campus?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    # username和password移到application-local.yml
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false

  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

logging:
  level:
    com.campus.product_management_seller: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

aliyun:
  oss:
    endpoint: https://oss-cn-shanghai.aliyuncs.com  # OSS endpoint
    access-key-id: LTAI5tGVpQGuxXuhSkRF3ak4         # AccessKey ID
    access-key-secret: i2Sg1uOtRR3UihOtWoQJMgAPMAVZGO    # AccessKey Secret
    bucket-name: avatars-bysuepsw25                   # bucket名称
    domain: avatars-bysuepsw25.oss-cn-shanghai.aliyuncs.com  # 你的bucket域名